/**
 * Authorization Management API
 * Authorization Management API
 *
 * OpenAPI spec version: 0.1.9
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {Attribute} from './attribute';


export interface PrivilegeWithAttributeValues {
  code?: string;
  name?: string;
  gatewayTypes?: Array<string>;
  attributes?: Array<Attribute>;
}
